config/routes.rb
SampleApp::Application.routes.draw do

  match 'users/:id/update_password', to: 'users#password', via: 'get'
    
  resources :users do
    member do
      get 'password'
      patch 'update_password'
    end
  end
  
  resources :clients
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :lots do
    get :autocomplete_phylum_name, :on => :collection
    get :autocomplete_l_class_name, :on => :collection
    get :autocomplete_genus_name, :on => :collection
    get :autocomplete_species_name, :on => :collection
    collection do
      post :edit_multiple
      put :update_multiple
      post :import
      post :quick
    end
  end
    
  resources :lot
  
  resources :batches do
    post 'savelot'
  end
  
  resources :commonnames
  
  resources :sampletypes
  
  resources :searches
  
  resources :search
  
  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/statistics', to: 'static_pages#statistics', via: 'get'
 
  

  

end

app/views/dashboard/_actions.html.erb
<div class="data-entry-header">
  <h2><i class="icon-exclamation-sign icon-white"></i> Actions <a href="#Actions" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
  </h2>
</div>
<p>Commonly used action shortcuts.</p>

<div id="Actions" class="collapse in display-none">
	<ul>
		<li>
			<%= link_to new_lot_path do %>
		     	<i class="icon-plus"></i>
		     	 Generate New Lot Number 
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "Enter a new sample's details and generate a new lot number."} %>
		     <% end %>
	     </li>
	     <li>
		     <%= link_to new_batch_path do %>
		     	<i class="icon-plus"></i>
		     	<i class="icon-plus"></i>
		     	 Generate Batch Lot Numbers
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "Enter a batch of new sample's details and generate a new lot numbers."} %>
		     <% end %>
		 </li>
		 <li>
		     <%= link_to lots_path do %>
		     	<i class="icon-list"></i>
		     	 Browse all Samples
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "List all sample lot numbers details stored in the LDMS."} %>
		     <% end %>
	     </li>	     
	     <li>
		     <%= link_to batches_path do %>
		     	<i class="icon-list"></i>
		     	 Browse all Batches
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "List all sample batches stored in the LDMS."} %>
		     <% end %>
	     </li>
		 <% if staff_user? %>
		     <li>
		     	<%= link_to clients_path do %>
		     		<i class="icon-list"></i>
		     		 Browse all Clients
		     		<%= render :partial => "layouts/hint", :locals => {:hint => "List all clients stored in the LDMS."} %>
		     	<% end %>
		     </li>
		     <li>
			     <%= link_to users_path do %>
			     	<i class="icon-list"></i>
			     	 Browse all Users
			     	<%= render :partial => "layouts/hint", :locals => {:hint => "List all user accounts stored in the LDMS."} %> 
			     <% end %>
		     </li>
		     <% end %>
	     <li>
		     <%= link_to edit_lot_path(Lot.last(1)) do %>
		     	<i class="icon-eye-open "></i>
		     	 Last Lot Number Generated (#<%= Lot.last(1)[0].id %>)
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "View the last lot number details, for the last lot generated by the LDMS."} %> 
		     <% end %>
	     </li>
	     <li>
		     <%= link_to lots_path(:all, format: "csv") do %>
		     	<i class="icon-download-alt "></i>
		     	 Download all samples details
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "Download all lot number details for all lots stored in the LDMS."} %>
		     <% end %>
	     </li>
	     <% if staff_user? %>
		     <li>
		     	<%= link_to statistics_path do %>
		     	<i class="icon-signal"></i>
		     	 Usage Statistics
		     	<%= render :partial => "layouts/hint", :locals => {:hint => "View usage statistics for the LDMS."} %>
		     	<% end %>
		     </li>
		 <% end %>
     </ul>
</div>

app/views/dashboard/_batches.html.erb
<div class="data-entry-header">
  <h2><i class="icon-list-alt icon-white"></i> Recent Batches <a href="#batches" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
  </h2>
</div>
<p>Last 5 Batches created.</p>
<div id="batches" class="collapse in display-none">
	<table class="table">
		<tr>
			<th>Description</th>
			<th>User</th>
			<th>Samples</th>
		</tr>
		<% Batch.where(:restriction => ['All', current_user.role]).order('id desc').limit(5).each do |batch| %>
			<tr>
				<td><%= link_to truncate(batch.name, :length => 20) + '..', edit_batch_path(batch) %></td>
				<td><%= link_to User.find(batch.user_id).name.humanize , user_path(User.find(batch.user_id))%></td>
				<td><%= Lot.where(batch_id: batch.id).count %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/dashboard/_mybatches.html.erb
<div class="data-entry-header">
	  <h2><i class="icon-star-empty icon-white"></i> My Recent Batches <a href="#my_batches" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  </h2>
</div>
<p>The last 5 batches you created.</p>

<div id="my_batches" class="collapse in">
	<% if !Batch.where(user_id: current_user.id).empty? %>
		<table class="table table-hover">
		<tr>
			<th>Description</th>
			<th>Client</th>
			<th>Samples</th>
			<th>Actions</th>
		</tr>		
		<% Batch.where(user_id: current_user.id).order('id desc').limit(5).each do |batch| %>
		    <tr>
				<td><%= link_to batch.name, edit_batch_path(batch) %></td>
				<td><%= link_to Client.find(batch.client_id).org.humanize , client_path(Client.find(batch.client_id))%></td>
				<td><%= Lot.where(batch_id: batch.id).count %></td>
				<td>
					<% if !Lot.where(batch_id: batch.id).empty? %>
						<%= link_to batch_path(batch.id, format: "csv") do %>
							<i class="icon-download-alt"></i> 
						<% end %>
					<% end %>
		    		<%= link_to edit_batch_path(batch.id) do %>
		    			<i class="icon-share"></i> 
		    		<% end %>
				</td>
			</tr>
		<% end %>		
		</table>
	<% else %>
		<p>You have not created any batches yet.</p>
	<% end %>
</div>

app/views/dashboard/_mylots.html.erb
<div class="data-entry-header">
	  <h2><i class="icon-star icon-white"></i> My Recent Lot Numbers <a href="#my_lots" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  </h2>
</div>
<p>The last 5 lot numbers you generated (not including those you updated).</p>

<div id="my_lots" class="collapse in">
	<% if !Lot.where(data_entered_by: current_user.id).empty? %>
		<table class="table table-hover">
		<tr>
			<th>Lot #</th>
			<th>Client</th>
			<th>Work Type</th>
			<th>Created</th>
		</tr>		
		<% Lot.where(data_entered_by: current_user.id).order('id desc').limit(5).each do |l| %>
		    <tr> 
			    <td> <%= link_to l.id, edit_lot_path(l.id) %> </td>
			    <td> <%= link_to Client.find(l.client_id).org.to_s.humanize, client_path(l.client_id)%></td>
			    <td> <%= l.commercial ? "Commerical" : "Non-Commerical" %></td>
			    <td> <%= time_ago_in_words(l.created_at) %> ago</td>
		    </tr>	    
		<% end %>		
		</table>
	<% else %>
		<p>You have not created any samples yet.</p>
	<% end %>
</div>

app/views/dashboard/_recentsamples.html.erb
<div class="data-entry-header">
	  <h2><i class="icon-time icon-white"></i> Recent Updated Samples <a href="#recent_lots" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  </h2>
</div>
<p>The Last 10 additions or updates to lots.</p>
<div id="recent_lots" class="collapse in">
	<table class="table table-hover">
	<tr>
		<th>Lot #</th>
		<th>Action</th>
		<th>By</th>
		<th>When</th>
	</tr>		
	<% PaperTrail::Version.order('id desc').limit(10).each do |v| %>
	    <tr> 
		    <td> <%= link_to v.item_id.to_s, edit_lot_path(v.item_id) %> </td>
		    <td> <%= v.event.to_s.humanize %>d</td>
		    <td> <%= link_to User.find(v.whodunnit.to_i).name.humanize, user_path(v.whodunnit) %></td>
		    <td> <%= time_ago_in_words(v.created_at) %> ago</td>
	    </tr>	    
	<% end %>		
	</table>
</div>

app/views/dashboard/_recentsearch.html.erb
<div class="data-entry-header">
	  <h2><i class="icon-search icon-white"></i> My Recent Searches <a href="#my_searches" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  </h2>
</div>
<p>The last 5 searches you performed.</p>

<div id="my_searches" class="collapse in">
	<% if Search.where(user_id: current_user.id).empty? %>
		<p>You have not performed any searches</p>
	<% else %>
		<table class="table">
		<tr>
			<th>Lot Range</th>
			<th>Client</th>
			<th>Site</th>
			<th>Biological classification</th>
			<th>Results</th>
		</tr>		
		<% Search.where(user_id: current_user.id).order('id desc').limit(5).each do |s| %>
		    <tr> 
			    <td> <%= if s.lot.presence
			    			s.lot.to_s
			    		else
			    	 		(!s.from.presence ? "0" : s.from.to_s) + " - " + (!s.to.presence ? "Max" : s.to.to_s)
			    	 	end  
			    	 %>
			    </td>
			    <td> 
			    	<% if !s.client.blank? %>
			    		<%= link_to Client.find(s.client).org.to_s.humanize, client_path(s.client) %>
			    	<% else %>
			    		All	
			    	<% end %>
			    </td>
			    <td> 
			    	<% if !s.site.blank? %>
			    		<%= s.site.to_s %>
			    	 <% else %>
			    	 	All
			    	 <% end %>
			    </td>
			    <td> <%= s.phylum.to_s + " " + s.l_class.to_s + " " + s.genus.to_s + " " + s.species.to_s %></td>
			    <td>
			    	<%= link_to search_path(s.id, format: "csv") do %>
						<i class="icon-download-alt"></i> 
					<% end %>
			    	<%= link_to search_path(s.id) do %>
			    		<i class="icon-share"></i> 
			    	<% end %>
			    </td>
		    </tr>	    
		<% end %>		
		</table>
		<div class="keys">
			<ul>
				<li>
					<i class="icon-share"></i> Go to
				</li>
				<li>
					<i class="icon-download-alt"></i> Download
				</li>
				<li>
					<b>Key:</b>
				</li>
			</ul>
		</div>
	<% end %>
</div>

app/views/dashboard/_stats.html.erb
<div class="data-entry-header">
  <h2><i class="icon-signal icon-white"></i> Statistics <a href="#stats" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
  </h2>
</div>
<p> Statistics for the Lot Database Management System</p>
<div id="stats" class="collapse in">
	<script type="text/javascript" charset="utf-8">
	
	$(function() {
		new Highcharts.Chart({
			chart: {
				renderTo: "com_chart"
			},
			title: {
				text: "Monthly Samples Totals"
			},
			subtitle: {
                text: 'Last 12 Months'
            },
			xAxis: {
				type: "datetime"
			},
			yAxis: {
				title: {
					text: "Lot Numbers Generated"
				}
			},
			series: [			
			<% { "Commercial" => Lot.commercial, "Non-commercial" => Lot.non_commercial, "Total" => Lot }.each do |name, lots| %>			
			{
				pointInterval: <%= 1.month.to_i * 1000 %>,
				pointStart: <%= 1.year.ago.to_i * 1000 %>,
				data: <%= (1.year.ago.to_date.beginning_of_month..Date.today).reject{|month| month.day != 1}.map { |month| lots.total_on(month).to_f }.inspect %>,
				name:  "<%= name %>"
			},
			<% end %>
			],
			credits: {
    			enabled: false
  		}
		});
		/*
		new Highcharts.Chart({
			chart: {
                type: 'area',
                renderTo: "client_chart"
            },
            title: {
                text: 'Commercial Client Share'
            },
            subtitle: {
                text: '6 Months Rolling'
            },
            xAxis: {
            	type: "datetime"
            },
            yAxis: {
				title: {
					text: "Lot Numbers Generated"
				}
            },
            plotOptions: {
                area: {
                    stacking: 'normal',
                    lineColor: '#666666',
                    lineWidth: 1,
                    marker: {
                        lineWidth: 1,
                        lineColor: '#666666'
                    }
                }
            },
            series: [
            	< Client.find(2..5).each do |c| >
            	{
            	name: '< c.org >',
            	pointInterval: <= 1.month.to_i * 1000 >,
            	pointStart: < 6.months.ago.to_i * 1000 >,
                data: <= (6.months.ago.to_date.beginning_of_month..Date.today).reject{|month| month.day != 1}.map { |month| Lot.total_client_on(month, 1).to_f }.inspect %>
            	}
            	< end >
            ],
            credits: {
    			enabled: false
  			}
       });*/
	});
	
	
	
	</script>	
	<div class="row">
		<div class="span6 offset0">
			<div id="com_chart" style="width:auto; height:300px;"></div>
		</div>
		<div class="span6 offset0">
			<div id="client_chart" style="width:auto; height:300px;"></div>
		</div>
	</div>
</div>

app/views/dashboard/_user.html.erb
<div class="data-entry-header">
  <h2>Hello, <%= current_user.name %>! <a href="#user" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
  </h2>
</div>
<div id="user" class="collapse in display-none">
	<p>Currently signed in as: <%= current_user.email %> </p>
	<ul>
		<li>
		<%= link_to  signout_path, method: "delete" do %>
		 <i class="icon-off"></i>
		  Sign out
		 <%= render :partial => "layouts/hint", :locals => {:hint => "Logout of the LDMS."} %>
		<% end %>
		</li>
	</ul>
</div>