config/routes.rb
SampleApp::Application.routes.draw do

  match 'users/:id/update_password', to: 'users#password', via: 'get'
    
  resources :users do
    member do
      get 'password'
      patch 'update_password'
    end
  end
  
  resources :clients
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :lots do
    get :autocomplete_phylum_name, :on => :collection
    get :autocomplete_l_class_name, :on => :collection
    get :autocomplete_genus_name, :on => :collection
    get :autocomplete_species_name, :on => :collection
    collection do
      post :edit_multiple
      put :update_multiple
      post :import
      post :quick
    end
  end
    
  resources :lot
  
  resources :batches do
    post 'savelot'
  end
  
  resources :commonnames
  
  resources :sampletypes
  
  resources :searches
  
  resources :search
  
  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/statistics', to: 'static_pages#statistics', via: 'get'
 
  

  

end

app/models/search.rb
class Search < ActiveRecord::Base
      
  def find_lots
    lots = Lot.order(:id)
    lots = lots.where("id >= ?", from ) if from.present?
    lots = lots.where("id <= ?", to ) if to.present?
    lots = lots.where(id: lot) if lot.present?
    lots = lots.where(client_id: client) if client.present?
    lots = lots.where("samp_id like ?", "%#{samp_id}%") if samp_id.present?
    lots = lots.where(commercial: com) if com.present?
    lots = lots.where("site like ?", "%#{site}%") if site.present?
    lots = lots.where("phylum like ?", "%#{phylum}%") if phylum.present?
    lots = lots.where("genus like ?", "%#{genus}%") if genus.present?
    lots = lots.where("l_class like ?", "%#{l_class}%") if l_class.present?
    lots = lots.where("species like ?", "%#{species}%") if species.present?
    lots
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def new 
  end
  
  def show
    @search = Search.find(params[:id])
    @lots = @search.find_lots
     respond_to do |format|
      format.html
      format.csv { send_data @lots.to_csv, filename: "LDMS-Search-" + @search.id.to_s + "-Results.csv"}
     end 
  end
  
  def create
    @search = Search.new(search_params)
    @search.user_id = current_user.id
    if @search.save
      redirect_to @search
    else
      flash[:alert] = "Search error please try again"
      redirect_to @search
    end
  end
  
  private

    def search_params
      params.require(:search).permit(:from,
                                     :to,
                                     :lot,
                                     :client,
                                     :samp_id,
                                     :com,
                                     :site,
                                     :phylum,
                                     :l_class,
                                     :genus,
                                     :species) 
    end
end

app/views/searches/_download.html.erb
<div class="data-entry-header">
	<h2><i class="icon-file icon-white"></i> Download Results <a href="#download" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	</h2>
</div>
<p>Download full search results.</p>
	
<div id="download" class="collapse in">
	<i class="icon-download-alt"></i> Download:
	<%= link_to search_path(format: "csv") do %>
		CSV <%= render :partial => "layouts/hint", :locals => {:hint => "Results downloads can be best viewed and edited with a spreadsheet package such as Excel."} %>
	<% end %>
</div>

app/views/searches/_new.html.erb
<div class="data-entry-header">
	<h2><i class="icon-search icon-white"></i> Search Parameters <a href="#search_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	</h2>
</div>
<p>Search Parameters are AND'd together to narrow search results and are all optional. Please note text fields are case sensitive.</p>

<div id="search_info" class="collapse in">
	<%= form_for(@search, :url => searches_path, :method => "post", :html => { :class => "form-horizontal", :id => "new_search" }) do |f| %>
	  <p>
		
		<div class="control-group"> 
	    	<%= f.label :from, "Lot Number Range", :class => "control-label" %>
	    	<div class="controls">
	    		<%= f.text_field :from, :placeholder => "From:" %>
	   			<%= f.text_field :to, :placeholder => "To:" %>
	   			<%= render :partial => "layouts/hint", :locals => {:hint => "Search for a range of lot numbers."} %>	   			
	    	</div>
		</div>
		
		<div class="control-group">
	  		<%= f.label :lot, "Single Lot Number", :class => "control-label" %>
	  		<div class="controls">
	    		<%= f.text_field :lot %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Search for a single lot number only."} %>
	    	</div>
		</div>
		
		<div class="control-group">
			<%= f.label :client, "Client", :class => "control-label" %>
			<div class="controls">
	    		<%= f.collection_select(:client, Client.all, :id, :org, {include_blank: 'All'}) %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Search for lot numbers for a single client only."} %>
	    	</div>
		</div>
		
		<div class="control-group">
			<%= f.label :samp_id, "Client Sample ID", :class => "control-label" %>
			<div class="controls">	
	    		<%= f.text_field :samp_id %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Search for a sample by the client sample id."} %>
	    	</div>
		</div>
		
		<div class="control-group">
			<%= f.label :com, "Commercial", :class => "control-label" %>
			<div class="controls">	
	    		<%= f.select :com, options_for_select([["All", ""], ["Commercial", true], ["Non-Commercial", false]], @search.com) %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Restrict search results to commercial or non-commercial samples."} %>
	    	</div>
		</div>
	
		<div class="control-group">
			<%= f.label :site, "Site", :class => "control-label" %>
			<div class="controls">	
	    		<%= f.text_field :site %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Search for samples from a particular site."} %>
	    	   	</div>
			</div>
			
		<div class="control-group">
			<%= f.label :phylum, "Biological classification", :class => "control-label" %>
			<div class="controls">	
	    		<%= f.text_field :phylum, :placeholder => "Phylum:" %>
	    		<%= f.text_field :l_class, :placeholder => "Class:" %>
	    		<%= render :partial => "layouts/hint", :locals => {:hint => "Search by biological classification, it is not necessary to specify all paramaters."} %>
	    		<br/><br/>
	    		<%= f.text_field :genus, :placeholder => "Genus:" %>
	    		<%= f.text_field :species, :placeholder => "Species:" %>
	    	   	</div>
			</div>	
		
		<div class="control-group">
			<div class="controls">	
				<%= button_tag( :class => "btn btn-primary") do %>
  					<i class="icon-search icon-white"></i> Search 
				<% end %>
	    	</div>
		</div>
	  </p>
	<% end %>
</div>

app/views/searches/_peak.html.erb
<a href="#" rel="popover" data-trigger: 'hover' data-html="true" data-original-title="<b> Lot Number <%= peak.id.to_s %> </b>" 
	data-content="	
	<table>
			<tr>
				<th>Client</th>
				<td><%= Client.find(peak.client_id).org.humanize %></td>
			</tr>
			<tr>
				<th>Commercial</th>
				<td><%= peak.commercial.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Accessable to</th>
				<td><%= peak.restriction.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Sample ID</th>
				<td><%= peak.samp_id %></td>
			</tr>
			<tr>
				<th>Sample type</th>
				<td><%= Sampletype.find(peak.sampletype_id).name %></td>
			</tr>
			<tr>
				<th>Common Name</th>
				<td><%= Commonname.find(peak.commonname_id).name %></td>
			</tr>
			<tr>
				<th>Phylum</th>
				<td><%= peak.phylum %></td>
			</tr>
			<tr>
				<th>Class</th>
				<td><%= peak.l_class %></td>
			</tr>
			<tr>
				<th>Genus</th>
				<td><%= peak.genus %></td>
			</tr>
			<tr>
				<th>Species</th>
				<td><%= peak.species %></td>
			</tr>
			<tr>
				<th>Sample Form</th>
				<td><%= peak.sample_form %></td>
			</tr>
			<tr>
				<th>Return Sample?</th>
				<td><%= peak.to_return.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Sample Returned?</th>
				<td><%= peak.returned.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Return Date</th>
				<td><%= (!peak.return_date.nil? ? ( l peak.return_date, format: :long) : "") %></td>
			</tr>
			<tr>
				<th>Archive Box</th>
				<td><%= peak.archive_box %></td>
			</tr>
			<tr>
				<th>Geographic region</th>
				<td><%= peak.region %></td>
			</tr>
			<tr>
				<th>Archeological site</th>
				<td><%= peak.site %></td>
			</tr>
			<tr>
				<th>Analysis by</th>
				<td><%= User.find(peak.analysis_by).name %></td>
			</tr>
			<tr>
				<th>Isotopes</th>
				<td><%= peak.isotopes.to_s.humanize %></td>
			</tr>
			<tr>
				<th>ZooMS</th>
				<td><%= peak.zooms.to_s.humanize %></td>
			</tr>
			<tr>
				<th>AAR</th>
				<td><%= peak.aar.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Lipid</th>
				<td><%= peak.lipid.to_s.humanize %></td>
			</tr>
			<tr>
				<th>DNA</th>
				<td><%= peak.dna.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Other Methods</th>
				<td><%= peak.analysis_other.to_s.humanize %></td>
			</tr>
			<tr>
				<th>Additional infomation</th>
				<td><%= peak.extra_info.to_s.humanize %></td>
			</tr>											
		</table>	
		">	
	<i class="icon-eye-open"></i></a>

app/views/searches/_results.html.erb
<div class="data-entry-header">
	<h2><i class="icon-th icon-white"></i> Search Results <a href="#results_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	</h2>
</div>
<% if @lots.empty? %>
	<p>No lots found, please review your search parameters and try again.</p>
<% else %>
	<p><%= @lots.count %> samples found. Search results are shown below click the column headers to sort.</p>
<% end %>
	
<div id="results_info" class="collapse in">
	<script>
	
	$(function(){
  		$("#tablesorted").tablesorter({
  			sortList: [[1,0]],
  			headers: {              
            	0: { 
                	sorter: false //select
            	},
            	6: {
            		sorter: false //ations
            	}
           }
        }
  		);
	});
	</script>
	<% if !@lots.empty? %>
		<%= form_tag edit_multiple_lots_path, method: :post do %>
			
			<table id="tablesorted" class="tablesorter table table-condensed">
				 <thead>
				 	<tr>
				      <th></th>
				      <th>Lot #</th>
				      <th>Client</th>
				      <th>Commercial</th>
				      <th>Site</th>
				      <th>Biological Classification</th>
				      <th>Actions</th>
				    </tr>
				 </thead>
				 <tbody> 
					 <% @lots.each do |lot| %>
					 	<tr>
					 		<td><%= check_box_tag "lot_ids[]", lot.id %></td>
					 		<td><%= lot.id.to_s %></td>
					 		<td><%= link_to Client.find(lot.client_id).org.to_s.humanize, client_path(lot.client_id) %></td>
					 		<td><%= lot.commercial ? "Yes" : "No" %></td>
					 		<td><%= lot.site %></td>
					 		<td><%= lot.phylum.to_s + " " + lot.l_class.to_s + " " + lot.genus.to_s + " " + lot.species.to_s %></td>
					 		<td><%= link_to edit_lot_path(lot) do %>
					 				<i class="icon-edit"></i> 
					 			<% end %>
					 			<%= link_to lot_path(lot) do %>
					 				<i class="icon-time"></i> 
					 			<% end %>
					 			<%= render :partial => "searches/peak", :locals => {:peak => lot} %>
					 		</td>
					 	</tr>
					 <% end %>
				 </tbody>
			</table>
			
			
			<div class="keys">
				<ul>
					<li>
						<i class="icon-eye-open"></i> Details
					</li>
					<li>
						<i class="icon-time"></i> History
					</li>
					<li>
						<i class="icon-edit"></i> Edit
					</li>
					<li>
						<b>Key:</b>
					</li>
				</ul>
			</div>
			<%= content_tag( :button, :type => :submit, :class => "btn btn-warning") do %>
	   			Edit Selected 
	   			<i class="icon-edit icon-white"></i>
			<% end %>
			<%= render :partial => "layouts/hint", :locals => {:hint => "Make updates to multiple samples simultaneously, by selecting them above."} %>
		<% end %>
	<% end %>
</div>

app/views/searches/show.html.erb
<% provide(:title, 'Search') %>
<h1>Search</h1>

<div class="row">
  <div class="span12 offset">
  	
		<%= render 'searches/new' %>
		
		<%= render 'searches/results' %>
		
		<%= render 'searches/download' %>
		
	</div>
</div>