config/routes.rb
SampleApp::Application.routes.draw do

  match 'users/:id/update_password', to: 'users#password', via: 'get'
    
  resources :users do
    member do
      get 'password'
      patch 'update_password'
    end
  end
  
  resources :clients
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :lots do
    get :autocomplete_phylum_name, :on => :collection
    get :autocomplete_l_class_name, :on => :collection
    get :autocomplete_genus_name, :on => :collection
    get :autocomplete_species_name, :on => :collection
    collection do
      post :edit_multiple
      put :update_multiple
      post :import
      post :quick
    end
  end
    
  resources :lot
  
  resources :batches do
    post 'savelot'
  end
  
  resources :commonnames
  
  resources :sampletypes
  
  resources :searches
  
  resources :search
  
  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/statistics', to: 'static_pages#statistics', via: 'get'
 
  

  

end

app/models/lot.rb
class Lot < ActiveRecord::Base

  scope :commercial, where(:commercial => true)
  scope :non_commercial, where(:commercial => false)

  def self.total_on(month)
    where("date(created_at) >= ? AND date(created_at) < ?", month.beginning_of_month, month.end_of_month).count
  end
  
  def self.total_client_on(month, id)
    where("date(created_at) >= ? AND date(created_at) < ? AND client_id = ? AND commercial = ?", month.beginning_of_month, month.end_of_month, id, true).count
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Lot_Number", "Client", "Client Contact Email" ,"Commercial", "Client_Sample_ID", "Sample_Type", "Common_Name",  "Phylum" , "Class" , "Genus" , "Species" , "Sample_Form" , "Region" , "Site" , "Analysis_by" , "Isotopes" , "ZooMS" , "AAR" , "Lipid" , "DNA" , "Other_Analysis" , "Return_Sample" , "Returned" , "Return_Date" , "Archive_Box" , "Extra_Info" , "Recieved_Date" , "Last_Updated" , "Created_by"] 
      all.each do |lot|
        @client = Client.find(lot.client_id)
        
        if lot.sampletype_id.presence
          @sampletype = Sampletype.find(lot.sampletype_id)
        end
        
        if lot.commonname_id.presence
          @commonname = Commonname.find(lot.commonname_id)     
        end
          
        if lot.analysis_by.presence
          @anal = User.find(lot.analysis_by)
        end  
        
        if lot.data_entered_by.presence
          @user = User.find(lot.data_entered_by)
        end
          
        csv << [lot.id , @client.org , @client.email , lot.commercial, lot.samp_id , @sampletype.name , @commonname.name , lot.phylum , lot.l_class , lot.genus , lot.species , lot.sample_form , lot.region , lot.site , @anal.name , lot.isotopes , lot.zooms , lot.aar , lot.lipid , lot.dna , lot.analysis_other , lot.to_return , lot.returned , lot.return_date.to_s.humanize , lot.archive_box , lot.extra_info , lot.created_at.to_s.humanize , lot.updated_at.to_s.humanize , @user.name]
      end
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      
    end
  end

  default_scope -> { order('id DESC') }
  validates :client_id, presence: true
  validates :commercial, :inclusion => {:in => [true, false]}
  validates :commonname_id, presence: true
  validates :analysis_by, presence: true
  validates :sample_form, presence: true
  validates :sampletype_id, presence: true
  validates :to_return, presence: true
  validates :samp_id, presence: true
  
  has_paper_trail
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
before_action :signed_in_user, only: [:edit, :update, :show, :index, :create, :destroy]
before_action :lot_restriction, only: [:edit, :update, :destroy, :show]

autocomplete :phylum, :name
autocomplete :l_class, :name
autocomplete :genus, :name
autocomplete :species, :name
  
  def show
    @lot = Lot.find(params[:id])
    @client = Client.find(@lot.client_id)
    @versions = @lot.versions
  end
  
  def new
    @lot = Lot.new(:commercial => false, :restriction => "All", :client_id => 2, :created_at => Time.now)
    flash.now[:notice] = "Please complete all mandatory and relevent fields for this sample."
  end
  
  def index
    @lots = Lot.paginate(page: params[:page], :per_page => 100)
    @lots_all = Lot.all
    respond_to do |format|
      format.html
      format.csv { send_data @lots_all.to_csv, filename: "LDMS-all-lots-" + Date.today.to_s + ".csv"}
     end 
  end
  
  def create
    @lot = Lot.new(lot_params)
    @lot.data_entered_by = current_user.id
    @lot.user_id = current_user.id
    @lot.returned = "NO"
    @lot.created_at = Time.now
    if @lot.save
      if @lot.batch_id.nil?
        flash[:success] = "Lot number: " + @lot.id.to_s + ", generated."
        redirect_to dashboard_path
      else
        flash[:success] = "Lot number: " + @lot.id.to_s + ", generated and added to batch." 
        redirect_to edit_batch_path(@lot.batch_id)
      end 
    else
      if @lot.batch_id.nil?
        render 'new'
      else
        @lots = Lot.where(batch_id: @lot.batch_id)
        @batch = Batch.find(@lot.batch_id) 
        render 'batches/edit'
      end 
    end
  end
  
  def edit
      @lot = Lot.find(params[:id])
      @user = User.find(@lot.data_entered_by)
      @client = Client.find(@lot.client_id)
  end
  
  def edit_multiple
    @lots = Lot.find(params[:lot_ids])
  end
  
  def update_multiple
    @lots = Lot.find(params[:lot_ids])
    @lots.reject! do |lot|
      lot.update_attributes(lot_params.reject { |k,v| v.blank? })
    end
    if @lots.empty?
      flash[:success] = "Lots updated."
      redirect_to dashboard_path
    else
      @lot = Lot.new(params[:lot])
      render "edit_multiple"
    end
  end
  
  def update
    @lot = Lot.find(params[:id])
    
    attributes = lot_params.clone
    
    if attributes[:returned] == "YES" && attributes[:return_date].blank? 
       attributes[:return_date] = Time.now
    end
    
    if @lot.update_attributes(attributes)
      flash[:success] = "Lot number:" + @lot.id.to_s + ", updated"
      redirect_to dashboard_path
    else
      @lot = Lot.find(params[:id])
      @user = User.find(@lot.data_entered_by)
      flash[:error] = "Error Lot number:" + @lot.id.to_s + ", was not updated"
      render 'edit'
    end
  end
  
  def import 
    Lot.import(params[:file])
    flash.now[:success] = "Lot numbers, imported."
    redirect_to dashboard_path
  end
  
  
  def quick
    @lots = Lot.where(samp_id: params[:id])
    if params[:id].empty?
      flash[:error] = "Search Parameters empty please try again."
    elsif @lot = Lot.find_by_id(params[:id])
      redirect_to edit_lot_path(@lot)
    elsif @lots.count == 1
      redirect_to edit_lot_path(@lots.first)    
    elsif @lots.count > 1
      flash[:error] = "Too many results found for search parameters " + params[:id].to_s + ". Please use full search feature."
      redirect_back_or dashboard_path
    else
      flash[:error] = "No lot number or sample ID found for search parameters " + params[:id].to_s + "."
      redirect_back_or dashboard_path
    end 
  end
  
  private

    def lot_params
      params.require(:lot).permit(:id,
                                  :client_id, 
                                  :commercial, 
                                  :commonname_id, 
                                  :analysis_by, 
                                  :samp_id,
                                  :sampletype_id,
                                  :commonname_id,
                                  :phylum,
                                  :l_class,
                                  :genus,
                                  :species,
                                  :sample_form,
                                  :to_return,
                                  :region,
                                  :site,
                                  :analysis_by,
                                  :extra_info,
                                  :created_at,
                                  :isotopes,
                                  :zooms,
                                  :aar,
                                  :lipid,
                                  :dna,
                                  :analysis_other,
                                  :returned,
                                  :archive_box,
                                  :return_date,
                                  :restriction,
                                  :batch_id,
                                  :town,
                                  :Latitude,
                                  :Longitude,
                                  :county,
                                  :district,
                                  :parish,
                                  :gisdataset
                                  )
    end
  
end

app/views/lots/_batchsubmitbtns.html.erb
<div class="pagination-centered">
	<%= button_tag( :class => "btn btn-success") do %>
		Generate Lot Number <i class="icon-ok icon-white"></i>
	<% end %>
	<%= link_to dashboard_path, class: "btn btn-danger" do %>
		Cancel <i class=" icon-remove icon-white"></i>
	<% end %>
	<%= render :partial => "layouts/hint", :locals => {:hint => "When samples prepopulate, additional submission buttons are displayed to speed up data entry."} %>
</div>

app/views/lots/_changelog.html.erb
<div class="data-entry-header">
  <h2>Changelog <a href="#history" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
  </h2>
</div>
<p>Histoy of changes to lot number <%= @lot.id.to_s %>.</p>

<div id="history" class="collapse in">

	<table class="table">
		<tr>
			<th>Action</th>
			<th>By</th>
			<th>When</th>
		</tr>		
		<% PaperTrail::Version.where(item_id: @lot.id).order('id asc').limit(10).each do |v| %>
		    <tr> 
			    <td> <%= v.event.to_s.humanize %>d</td>
			    <td> <%= link_to User.find(v.whodunnit.to_i).name.humanize, user_path(v.whodunnit) %></td>
			    <td> <%= time_ago_in_words(v.created_at) %> ago</td>
		    </tr>	    
		<% end %>		
	</table>

</div>

app/views/lots/_commonbioclass.html.erb
<a href="#" rel="popover" data-html="true" data-original-title="<b>Common Taxonomic Classifications</b>" 
	data-content="
	<table class='table table-condensed'>
		<tr>
			<th></th>
			<th>Phylum</th>
			<th>Class</th>
			<th>Genus</th>
			<th>Species</th>
		</tr>
		<% Commonname.where(hint: true).each do |cn| %>
			<tr>
				<td><%= cn.name.humanize %></td>
				<td><%= cn.phylum %></td>
				<td><%= cn.l_class %></td>
				<td><%= cn.genus %></td>
				<td><%= cn.species %></td>
			</tr>
		<% end %>
	</table>
	">common taxonomic classifications</a>

app/views/lots/edit.html.erb
<% provide(:title, 'Update lot') %>
<h1>Lot Number: <%= @lot.id.to_s %></h1>

<div class="row">
  <div class="span5 offset0">

	<%= render 'lots/editactions' %>
	<%= render 'lots/changelog' %>		

	
 </div>
  <div class="span7 offset0">
	  <%= form_for(@lot, :html => { :class => "form-horizontal" }) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
		<%= render :partial => 'lots/form', :locals => { :f => f, :extra_btn => false, :collapse_in => false } %>
	  
  		<div class="pagination-centered">
	 		<%= f.submit "Save changes", class: "btn btn-warning" %>
		</div>
	  <% end %>
  </div>
</div>

app/views/lots/edit_multiple.html.erb
<h1>Edit Selected Lots</h1>
<h2>Updates will be applied to all selected Lots.</h2>

<div class="data-entry-header">
	<h2><i class="icon-list icon-white"></i> Update Fields <a href="#fields" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	</h2>
</div>
<p>Fields updated here will be applied to all selected lots upon form submission. Please note, not all fields are avaliable to for multiple edit.</p>

<div id="fields" class="collapse in">
  <%= form_tag update_multiple_lots_path, :class => "form-horizontal", method: :put do %>
    <%= fields_for :lot do |f| %>
	
	<div class="row">
	  <div class="span7 offset0">
		  <div class="data-entry-header">
		  	<h2>Client Info <a href="#client_info" data-toggle="collapse" class="pull-right icon-resize-vertical icon-white"></a>
		  	</h2>
		  </div>
		  <p>Infomation about the client.</p>
		  
		  <div id="client_info" class="collapse">
			  <div class="control-group">
			  	<%= f.label :client_id, "Client", :class => "control-label" %>	  	
			  	<div class="controls">
			  		<%= f.collection_select(:client_id, Client.all, :id, :org, include_blank: true ) %> 
					<%= render :partial => "layouts/hint", :locals => {:hint => "Which Organisation sent the sample, for student samples the client is 'University of York'."} %>
			  	</div>
			  </div>
			  
			  <div class="control-group">
			  	<%= f.label :commercial, :class => "control-label" %>
			  	<div class="controls">
		  			<%= f.select :commercial, options_for_select([["Non-Commercial", false], ["Commercial", true]]), include_blank: true %>
					<%= render :partial => "layouts/hint", :locals => {:hint => "Is this a commercial peice of work?"} %>
			  	</div>
			  </div> 
			  
		  </div>
		  
		  <div class="data-entry-header">
	  	<h2>Sample Details <a href="#samp_det" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  	</h2>
	  </div>
	  <p>Details about the sample, unknown fields should be left blank to be completed when known.</p>
	  
	  <div id="samp_det" class="collapse">
		  <div class="control-group">
		  	<%= f.label :sampletype_id, "Sample type", :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.collection_select(:sampletype_id, Sampletype.all, :id, :name, include_blank: true) %>
		  		<%= render :partial => "layouts/hint", :locals => {:hint => "A high level description of the sample."} %>
		    </div>
		  </div>
		  
		  <div class="control-group">
		  	<%= f.label :commonname_id, "Common Name", :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.collection_select(:commonname_id, Commonname.all, :id, :name, include_blank: true) %>
		  		<%= render :partial => "layouts/hint", :locals => {:hint => "The commonly used name for this sample."} %>
		    </div>
		  </div>
		  
		  <p>Type a couple of letters for suggestions, if unknown please leave biological classification fields blank.</p>
		  
		  <div class="control-group">
		  	<%= f.label :phylum, :class => "control-label" %>
		  	<div class="controls">	      		
	      		<%= f.autocomplete_field :phylum, autocomplete_phylum_name_lots_path, :placeholder => "Type for suggestions" %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "Start Typing the first few letters for suggested values."} %>
		    </div>
		  </div>
		  
		  <div class="control-group">
		  	<%= f.label :l_class, "Class", :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.autocomplete_field :l_class, autocomplete_l_class_name_lots_path, :placeholder => "Type for suggestions" %>
		    	<%= render :partial => "layouts/hint", :locals => {:hint => "Start Typing the first few letters for suggested values."} %>
		    </div>
		  </div>
		  
		  <div class="control-group">
		  	<%= f.label :genus, :class => "control-label" %>
		  	<div class="controls">
	     		 <%= f.autocomplete_field :genus, autocomplete_genus_name_lots_path, :placeholder => "Type for suggestions" %>
		    	 <%= render :partial => "layouts/hint", :locals => {:hint => "Start Typing the first few letters for suggested values."} %>
		    </div>
		  </div>
		  
		  <div class="control-group">
		  	<%= f.label :species, :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.autocomplete_field :species, autocomplete_species_name_lots_path, :placeholder => "Type for suggestions" %>
		    	<%= render :partial => "layouts/hint", :locals => {:hint => "Start Typing the first few letters for suggested values."} %>
		    </div>
		  </div>
	  </div>
	  
	  <div class="data-entry-header">  
	  	<h2>Sample Storage Info <a href="#store_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  	</h2>
	  </div>
	  <p>Infomation here helps identify and manage samples.</p>
	  
	  <div id="store_info" class="collapse">
		  <div class="control-group">
		  	<%= f.label :sample_form, "Sample Form", :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.text_field :sample_form, :placeholder => "eg. 'Foil pack' or 'test tube'" %>
		  		<%= render :partial => "layouts/hint", :locals => {:hint => "Description of how the sample is packed, to aid in identifying the sample."} %>	
		    </div>
		  </div>
		    	  
		  <div class="control-group">
		  	<%= f.label :to_return, "Return sample when finished?", :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.select :to_return, options_for_select([["Yes", "YES"], ["No (destroy)", "NO"], ["Archive", "ARCHIVE"]]), include_blank: true %>
		  		<%= render :partial => "layouts/hint", :locals => {:hint => "What should happen to the sample once analysis is complete."} %>
		    </div>
		  </div>
		  
		  <div class="control-group">
			<%= f.label :returned, "Sample Returned?", :class => "control-label" %>
			<div class="controls">
				<%= f.select :returned, options_for_select([["Yes", "YES"], ["No", "NO"]]), include_blank: true %>
				<%= render :partial => "layouts/hint", :locals => {:hint => "Has this sample been returned?"} %>
			</div>
		  </div>
		  
		  <div class="control-group">
	  		<%= f.label :archive_box, "Archive Box", :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.text_field :archive_box, :placeholder => "eg. Archive Room 1 Box 2" %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Where is this item archived?"} %>
	    	</div>
		  </div>
		  
	  	  <div class="control-group">
	  	  	<%= f.label :return_date, "Date Returned", :class => "control-label" %>
	  	  		<div class="controls">
	      		<%= f.date_field :return_date %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "When was this sample returned leave blank to autofil upon return."} %>
	 	    </div>
		  </div>	
   </div>  
	  
	<div class="data-entry-header">  	  
	  	<h2>Geographic Info <a href="#geo_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  	</h2>
	  </div>
	  <p>Geographic Infomation about where the sample was taken from.</p>
	  
	  <div id="geo_info" class="collapse">
		  <div class="control-group">
		  	<%= f.label :region, "Geographic region", :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.text_field :region, :placeholder => "eg. North Yorks" %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "The area the sample came from."} %>
		    </div>
		  </div>
	  
		  <div class="control-group">
		  	<%= f.label :site, "Archeological site", :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.text_field :site, :placeholder => "eg. York - Heslington East" %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "The specific site the sample came from."} %>
		    </div>
		  </div>
	  </div>	  
		  
	  <div class="data-entry-header">    
  	  	<h2>Analysis <a href="#anal_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  	</h2>
  	  </div>
  	  <p> Infomation about analysis and who will be carrying it out.</p>
  	  
  	  <div id="anal_info" class="collapse">
	  	  <div class="control-group">
	  	  	<%= f.label :analysis_by, "Analysis to be carried out by", :class => "control-label" %>
	  	  	<div class="controls">
		  		<%= f.collection_select(:analysis_by, User.all, :id, :name, include_blank: true) %>
		  		<%= render :partial => "layouts/hint", :locals => {:hint => "The student or member of staff who will be carrying out the analysis work."} %>
		    </div>
		  </div>
	  
	  	<p>Please select all methods that apply:</p>
	    <div class="control-group">
	  		<%= f.label :isotopes, :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.select :isotopes, options_for_select([["Yes", true], ["No", false]]), include_blank: true  %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Will Isotope analysis be conducted on this sample."} %>
	  		</div>
		</div>
	  
		<div class="control-group">	  
	  		<%= f.label :zooms, "ZooMS", :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.select :zooms, options_for_select([["Yes", true], ["No", false]]), include_blank: true  %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Will ZooMS analysis be conducted on this sample."} %>
	  		</div>
		</div>
			  	
	  	<div class="control-group">
	  		<%= f.label :aar, "AAR", :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.select :aar, options_for_select([["Yes", true], ["No", false]]), include_blank: true  %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Will AAR analysis be conducted on this sample."} %>
	  		</div>
		</div>
			  	
	  	<div class="control-group">
	  		<%= f.label :lipid, :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.select :lipid, options_for_select([["Yes", true], ["No", false]]), include_blank: true  %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Will Lipid analysis be conducted on this sample."} %>
	  		</div>
		</div>
			  	
	  	<div class="control-group">
	  		<%= f.label :dna, "DNA", :class => "control-label" %>
	  		<div class="controls">
	  			<%= f.select :dna, options_for_select([["Yes", true], ["No", false]]), include_blank: true  %>
	  			<%= render :partial => "layouts/hint", :locals => {:hint => "Will DNA analysis be conducted on this sample."} %>
	  		</div>
		</div>
			  
	  	<div class="control-group">
		  	<%= f.label :analysis_other, "Other Methods:", :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.text_field :analysis_other, :placeholder => "" %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "Any other analysis to be conducted on this sample."} %>
		    </div>
		  </div>
	  </div>  
	
	  <div class="data-entry-header">    
  	  	<h2>Extra Info <a href="#extra_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	  	</h2>
  	  </div>
  	  <p>Any extra infomation not recorded elsewhere.</p>
  	  
  	  <div id="extra_info" class="collapse">
		  <div class="control-group">
		  	<%= f.label :extra_info, "Additional infomation", :class => "control-label" %>
		  	<div class="controls">
	      		<%= f.text_area :extra_info, :placeholder => "" %>
	      		<%= render :partial => "layouts/hint", :locals => {:hint => "Any additional infomation on this sample not recorded elsewhere."} %>
		    </div>
		  </div>
	  </div>
	  
	  	<%= content_tag( :button, :type => :submit, :class => "btn btn-warning") do %>
			Update Selected 
			<i class="icon-edit icon-white"></i>
		<% end %>
		<%= render :partial => "layouts/hint", :locals => {:hint => "All selected lots will be updated upon submission."} %>	
	  </div>
	  
	  <div class="span4 offset1">
	  	<div class="data-entry-header">
			<h2><i class="icon-ok-sign icon-white"></i> Selected Lots <a href="#selected_lots" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
			</h2>
		</div>
		<p>All lots selected for update.</p>
			
		<div id="selected_lots" class="collapse in">
		  <table class="table table-condensed">
		  	<tr>
		  		<th>Lot #</th>
		  		<th>Sample ID</th>
		  	</tr>
			<% @lots.each do |lot| %>
				<tr>
			  		<td><%= lot.id.to_s %>
			  			<%= hidden_field_tag "lot_ids[]", lot.id %>
			  		</td>
			  		<td>
			  			<%= lot.samp_id.to_s %>
			  		</td>
			  	</tr>
			<% end %>
		  </table>
		</div>
	  	
	  </div>
	</div>
  <% end %>  
<% end %>
</div>

app/views/lots/index.html.erb
<% provide(:title, 'All Samples') %>
<h1>All Sample Lot Numbers</h1>
<h2>There are currently <%= Lot.all.count %> samples stored in the LDMS.</h2>
<div class="row">
  <div class="span12 offset0">
		
		<div class="data-entry-header">
	<h2>Lot Numbers <a href="#results_info" data-toggle="collapse" class="pull-right  icon-resize-vertical icon-white"></a>
	</h2>
</div>
<p>All lot numbers in sets of 100, most recent first.</p>
	
<div id="results_info" class="collapse in">

	<%= will_paginate  %>
	
	<table class="table">
	  <tr>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Lot Number", :hint => "The unique lot number generated by the LDMS for this sample"} %></th>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Client", :hint => "The oraganisation to which the sample belongs."} %></th>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Sample ID", :hint => "An identifier provided by the client or student for this sample."} %></th>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Analysis by", :hint => "Who will perform the analysis on this sample."} %></th>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Last updated by", :hint => "Who last updated this sample."} %></th>
	    <th><%= render :partial => "layouts/wordhint", :locals => {:word_hint => "Options", :hint => "Options associated with sample such as edit or view history."} %></th>
	  </tr>
	
	  <% @lots.each do |lot| %>
	    <tr>
	      <td>
	      	<%= lot.id.to_s %>
	      </td>
	      <td>
	      	<%= link_to Client.find(lot.client_id).org.to_s.humanize, client_path(lot.client_id) %>
	      </td>
	      <td>
	      	<%= lot.samp_id.to_s %>
	      </td>	
	      <td>
	      	<%= link_to User.find(lot.analysis_by).name.humanize, user_path(lot.analysis_by) %>
	      </td>
	      <td>
	      	<%= link_to User.find(lot.data_entered_by).name.humanize, user_path(lot.data_entered_by) %>
	      </td>	
	      <td>
	      	<%= link_to edit_lot_path(lot) do %><i class="icon-edit"></i><% end %> <%= link_to lot_path(lot) do %><i class="icon-time"></i><% end %>
	      </td>	
	    </tr>
	  <% end %>
	</table>
	<div class="keys">
			<ul>
				<li>
					<i class="icon-time"></i> History
				</li>
				<li>
					<i class="icon-edit"></i> Edit
				</li>
				<li>
					<b>Key:</b>
				</li>
			</ul>
		</div>
	<%= will_paginate  %>

</div>
		
	</div>
</div>