config/routes.rb
SampleApp::Application.routes.draw do

  match 'users/:id/update_password', to: 'users#password', via: 'get'
    
  resources :users do
    member do
      get 'password'
      patch 'update_password'
    end
  end
  
  resources :clients
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :lots do
    get :autocomplete_phylum_name, :on => :collection
    get :autocomplete_l_class_name, :on => :collection
    get :autocomplete_genus_name, :on => :collection
    get :autocomplete_species_name, :on => :collection
    collection do
      post :edit_multiple
      put :update_multiple
      post :import
      post :quick
    end
  end
    
  resources :lot
  
  resources :batches do
    post 'savelot'
  end
  
  resources :commonnames
  
  resources :sampletypes
  
  resources :searches
  
  resources :search
  
  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/statistics', to: 'static_pages#statistics', via: 'get'
 
  

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Lot Database Management System - An <a href="http://www.york.ac.uk/archaeology/">Archaeology</a> and <a href="http://york.ac.uk/">University of York</a> service.     
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "LDMS", (signed_in? ? dashboard_path : root_path), id: "logo" %>
      <nav>
        <ul class="nav pull-right">
        <% if signed_in? %>
          <li><%= link_to dashboard_path do %>         	
          	<i class="icon-home icon-white"></i> Dashboard
          	<% end %>
          </li>
        <% end %>
          <%if staff_user? %>
			<li id="fat-menu" class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			    <i class="icon-cog icon-white"></i> Config <b class="caret"></b>
			  </a>
			  <ul class="dropdown-menu">
			    <li>
			    	<%= link_to users_path do %>
			    	<i class="icon-list"></i> All Users
			    	<% end %>
			    </li>
			    <li>
			    	<%= link_to new_user_path do %>
			    	<i class="icon-plus"></i> New User
			    	<% end %>
			    </li>
			    <li class="divider"/>
			    <li>
			    	<%= link_to clients_path do %>
			    	<i class="icon-list"></i> All Clients
			    	<% end %>
			    </li>
			    <li>
			    	<%= link_to new_client_path do %>
			    	<i class="icon-plus"></i> New Client
			    	<% end %>
			    </li>
			    <li class="divider"/>
			    <li>
			    	<%= link_to commonnames_path do %>
			    	 <i class="icon-list"></i> All Common Names
			    	<% end %>
			    </li>
			    <li>
			    	<%= link_to new_commonname_path do %>
			    		<i class="icon-plus"></i> New Common Name
			    	<% end %>
			    </li>
			    <li class="divider"/>
			    <li>
			    	<%= link_to sampletypes_path do %>
			    	 <i class="icon-list"></i> All Sample Types
			    	<% end %>
			    </li>
			    <li>
			    	<%= link_to new_sampletype_path do %>
			    		<i class="icon-plus"></i> New Sample Type
			    	<% end %>
			    </li>
			  </ul>
			</li>
          <% end %>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <i class="icon-user icon-white"></i> Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                	<%= link_to current_user do %>
                	<i class="icon-eye-open"></i> Profile
                	<%end %>
                </li>
                <li>
                	<%= link_to edit_user_path(current_user) do %>
                	<i class="icon-wrench"></i> Account Settings
                	<% end %>
                </li>
                <li>
                	<%= link_to update_password_user_path(current_user) do %>
                	<i class="icon-lock"></i> Change Password
                	<% end %>
                </li>
                <li class="divider"/>
                <li>
                  <%= link_to  signout_path, method: "delete" do %>
                 	<i class="icon-off"></i> Sign out
                  <% end %>
                </li>
              </ul>
            </li>
            <li>
	          	<div id="header-search">
		        	<%= form_tag quick_lots_path, :class => "form-search", method: :post do %>
		        	 <div class="input-append">
		        		<%= text_field_tag :id, nil, :placeholder => "Lot # or ID", :class => "input-small search-query" %>
		        		<%= button_tag(type: "submit", class: "btn") do %>
		        			<i class="icon-search"></i>
		        		<% end %>
		        	 </div>
		        	<% end %>
	        	</div>
        	</li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_hint.html.erb
<div class="hint">
	<a href="#" rel="tooltip" data-placement="right" data-original-title="<%= hint %>">
		<i class="icon-info-sign"></i>
	</a>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_wordhint.html.erb
<div class="wordhint">
	<a href="#" rel="tooltip" data-placement="top" data-original-title="<%= hint %>">
		<%= word_hint %>
	</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script type='text/javascript' src='https://www.google.com/jsapi'></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    	 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>